# Generated by Django 5.1.4 on 2024-12-13 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='date',
        ),
        migrations.AddField(
            model_name='issuance',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время выдачи'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
