# Generated by Django 5.1.4 on 2024-12-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_issuance_date_issuance_date_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_weight',
        ),
        migrations.AlterField(
            model_name='cart',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='method_of_payment',
            field=models.CharField(choices=[('cash', 'наличка'), ('mbank', 'мбанк'), ('optima', 'optima')], max_length=30, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('issued', 'Выдан'), ('not_issued', 'Не выдан')], default='not_issued', max_length=20, verbose_name='Статус'),
        ),
    ]
